--------------------------------------------------
-- DROP ALL OBJECTS
-- Run this script to drop all database objects
-- Use this if you need to start fresh
-- Usage: @00_drop_all.sql
--------------------------------------------------

PROMPT ========================================
PROMPT Dropping all LogiTrack database objects
PROMPT ========================================
PROMPT 

-- Drop Views (with error handling)
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW v_kpi_dashboard';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW v_vehicules_entrepots';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW v_colis_details';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW v_livraisons_details';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

PROMPT Views dropped...

-- Drop Package Body and Package
BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE BODY pkg_logitrack';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE pkg_logitrack';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

PROMPT Package dropped...

-- Drop Procedures (if they exist separately)
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE p_create_livraison_if_needed';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE p_create_new_livraison_if_needed';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

PROMPT Procedures dropped...

-- Drop Triggers (with error handling)
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_livraison_depart_create';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_livraison_arrivee';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_livraison_depart';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_colis_annulation_unassign';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_colis_assign_price';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_hist_liv_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_hist_colis_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_colis_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_livraisons_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_clients_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_vehicules_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_entrepots_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_utilisateurs_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

PROMPT Triggers dropped...

-- Drop Tables (with CASCADE CONSTRAINTS to handle foreign keys)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE historique_statut_livraisons CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE historique_statut_colis CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE colis CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE livraisons CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE vehicules CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE clients CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE entrepots CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE utilisateurs CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

PROMPT Tables dropped...

-- Drop Sequences
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_hist_liv';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_hist_colis';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_colis';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_livraisons';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_clients';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_vehicules';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_entrepots';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_utilisateurs';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

PROMPT Sequences dropped...

COMMIT;

PROMPT 
PROMPT ========================================
PROMPT All objects dropped successfully!
PROMPT ========================================
PROMPT 
PROMPT You can now run @install.sql to reinstall everything
PROMPT 



